// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArKvD0an7K70tb-fdmwZAtRE4EwU1tiKo',
    appId: '1:604076347707:web:cfcca7c9366da2a47f271e',
    messagingSenderId: '604076347707',
    projectId: 'fooddeliveryapp-90625',
    authDomain: 'fooddeliveryapp-90625.firebaseapp.com',
    storageBucket: 'fooddeliveryapp-90625.firebasestorage.app',
    measurementId: 'G-8SBVBTCWSD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqJXoJkA3mS9yMV2UxyTAWtnEwNcUwxpE',
    appId: '1:604076347707:android:1a80dfce5cd036f37f271e',
    messagingSenderId: '604076347707',
    projectId: 'fooddeliveryapp-90625',
    storageBucket: 'fooddeliveryapp-90625.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDOIRl0PGaLhIzT9eE3aPTWP8ljhj6vEY',
    appId: '1:604076347707:ios:9473af5a376f37927f271e',
    messagingSenderId: '604076347707',
    projectId: 'fooddeliveryapp-90625',
    storageBucket: 'fooddeliveryapp-90625.firebasestorage.app',
    iosBundleId: 'com.dummyapps.fooddelivery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDOIRl0PGaLhIzT9eE3aPTWP8ljhj6vEY',
    appId: '1:604076347707:ios:9473af5a376f37927f271e',
    messagingSenderId: '604076347707',
    projectId: 'fooddeliveryapp-90625',
    storageBucket: 'fooddeliveryapp-90625.firebasestorage.app',
    iosBundleId: 'com.dummyapps.fooddelivery',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArKvD0an7K70tb-fdmwZAtRE4EwU1tiKo',
    appId: '1:604076347707:web:09b4f5f8b7f6d5677f271e',
    messagingSenderId: '604076347707',
    projectId: 'fooddeliveryapp-90625',
    authDomain: 'fooddeliveryapp-90625.firebaseapp.com',
    storageBucket: 'fooddeliveryapp-90625.firebasestorage.app',
    measurementId: 'G-8S6HZW59WN',
  );
}
